[Script]
# 拦截 https://auth.chippercash.com/pin/validate 请求并执行脚本 (http-response)
bypass_pin_validation_response = type=http-response,pattern=^https:\/\/auth\.chippercash\.com\/pin\/validate,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chucyfunny/Chipper/main/passpin.js

# 拦截 https://auth.chippercash.com/pin/validate 请求并执行脚本 (http-request)
bypass_pin_validation_request = type=http-request,pattern=^https:\/\/auth\.chippercash\.com\/pin\/validate,requires-header=1,max-size=0,script-path=https://raw.githubusercontent.com/chucyfunny/Chipper/main/seilfe.js

[MITM]
hostname = auth.chippercash.com
